version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: records_registry
    environment:
      POSTGRES_DB: records_registry_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "records_registry_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: records_app
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/records_registry_db

volumes:
  postgres_data:
  uploads_data:
